### ISSUE TITLE
Pls, help? Where rep?

### ISSUE THREAD

**Issue by Juranik** [MichiyamaKaren/ultimatevocalremover-webui#5]
`Cloning into 'Dora'...
remote: Repository not found.
fatal: repository 'https://github.com/soudabot/Dora/' not found`

**Comment by Aldair502** [comment]
FUCK. SORRY LET ME FIX IT

**Comment by Aldair502** [comment]
use this one insted https://github.com/Aldair502/Dora

**Comment by MichiyamaKaren** [comment]
Fixed with @Aldair502 's modification on Dora
